manifest:
  remotes:
    - name: splitkb
      url-base: https://github.com/splitkb
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk-halcyon-module
      remote: splitkb
      revision: main
      import: config/west.yml
  self:
    path: config
